SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP SCHEMA IF EXISTS `ChallengeXPandIT` ;

CREATE SCHEMA IF NOT EXISTS `ChallengeXPandIT` DEFAULT CHARACTER SET utf8 ;
USE `ChallengeXPandIT` ;

DROP TABLE IF EXISTS `ChallengeXPandIT`.`movie` ;

CREATE TABLE IF NOT EXISTS `ChallengeXPandIT`.`movie` (
  `id` INT NOT NULL,
  `name` VARCHAR(150) NOT NULL DEFAULT 'Nome',
  `date` VARCHAR(150) NOT NULL DEFAULT 'Date',
  `rating` VARCHAR(150) NOT NULL DEFAULT 'Rating',
  `revenue` VARCHAR(150) NOT NULL DEFAULT 'Revenue',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `ChallengeXPandIT`.`movie` (`id` ASC) VISIBLE;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
